/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aplikacja2023;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(CinemaManager.class, args);
    }
}
